log:
  level: "INFO"
  format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"

files:
  root_directory: "/home/username/Downloads"
  source_docs_directory: "source_docs"

db:
  persist_dir: "db"
  chrome_db_impl: "duckdb+parquet"
  anonymized_telemetry: false

parallelism:
  use_max_cpu_threads: true
  default_threads: 8
  max_processes: 8


embeddings:
  embedding_model_name: "hkunlp/instructor-large"
