log:
  level: "DEBUG"
  format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"

files:
  root_directory: "${PRADA_RAGE_ROOT_DIRECTORY:~/.rage}"
  source_docs_directory: "${PRADA_RAGE_SOURCE_DOCS_DIR:source_docs}"

rdbms:
  host: ${PRADA_RAGE_RDBMS_HOST:localhost}
  port: ${PRADA_RAGE_RDBMS_PORT:5432}
  database: ${PRADA_RAGE_RDBMS_DBNAME:rage}
  username: ${PRADA_RAGE_RDBMS_USERNAME:postgres}
  password: ${PRADA_RAGE_RDBMS_PASSWORD:postgres}

vectorstore:
  persist_dir: "${PRADA_RAGE_VECTORSTORE_DIR:db}"

embedding_service:
  embedding_model_name: ${PRADA_RAGE_EMBEDDING_MODEL_NAME:hkunlp/instructor-large}
  device_type: ${PRADA_RAGE_EMBEDDING_DEVICE_TYPE:cpu}
  chunk_size: ${PRADA_RAGE_EMBEDDING_CHUNK_SIZE:1000}
  chunk_overlap: ${PRADA_RAGE_EMBEDDING_CHUNK_OVERLAP:200}

localgpt:
  llm_model: ${PRADA_RAGE_LOCALGPT_LLM_MODEL:llama2-7b-chat}
