[tool.poetry]
name = "prada-rage"
version = "0.1.0"
description = ""
authors = ["maany <imptodefeat@gmail.com>"]
readme = "README.md"
packages = [{include = "lib"}]

[tool.poetry.dependencies]
python = "^3.10"
dependency-injector = "^4.41.0"
python-dotenv = "^1.0.0"
pyyaml = "^6.0.1"
googlesearch-python = "^1.2.3"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
