log:
  level: "DEBUG"
  format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"

files:
  root_directory: "~/.rage-test"
  source_docs_directory: "source_docs"

db:
  persist_dir: "db"
  chrome_db_impl: "duckdb+parquet"
  anonymized_telemetry: false

embeddings_service:
  embedding_model_name: "hkunlp/instructor-large"
  device_type: "cpu"
  chunk_size: 1000
  chunk_overlap: 200
