"""message can refer to multiple source_docs

Revision ID: 0dfd893f6bc7
Revises: fe278579d45d
Create Date: 2023-08-23 20:20:18.602395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dfd893f6bc7"
down_revision: Union[str, None] = "fe278579d45d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_base_message_association",
        sa.Column("knowledge_base_id", sa.Integer(), nullable=True),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["knowledge_base_id"],
            ["knowledge_base.id"],
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
    )
    op.add_column("messages", sa.Column("source_document_metadata", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "source_document_metadata")
    op.drop_table("knowledge_base_message_association")
    # ### end Alembic commands ###
