"""user, notes

Revision ID: a66a432bf8a8
Revises: 
Create Date: 2023-08-22 19:16:59.704112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a66a432bf8a8"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("DOCUMENT", "CONVERSATION", "USER", name="notetype"), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="NOTE_CREATED_NN"),
        sa.CheckConstraint("DELETED IS NOT NULL", name="NOTE_DELETED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="NOTE_UPDATED_NN"),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user",
        sa.Column("prada_user_uuid", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("CREATED_AT IS NOT NULL", name="USER_CREATED_NN"),
        sa.CheckConstraint("UPDATED_AT IS NOT NULL", name="USER_UPDATED_NN"),
        sa.PrimaryKeyConstraint("prada_user_uuid"),
        mysql_engine="InnoDB",
    )
    op.create_table(
        "user_note",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["note.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.prada_user_uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_note")
    op.drop_table("user")
    op.drop_table("note")
    # ### end Alembic commands ###
