"""research_context-non-null-goal, unique_lfn

Revision ID: b5cd9a16f6ea
Revises: d9841daf0019
Create Date: 2023-08-21 15:52:13.955394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5cd9a16f6ea'
down_revision: Union[str, None] = 'd9841daf0019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'documents', ['lfn'])
    op.create_unique_constraint(None, 'vector_stores', ['lfn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vector_stores', type_='unique')
    op.drop_constraint(None, 'documents', type_='unique')
    # ### end Alembic commands ###
