"""add conversations, messages

Revision ID: cd6cbc865534
Revises: 20658262aa85
Create Date: 2023-08-23 19:23:29.571962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6cbc865534'
down_revision: Union[str, None] = '20658262aa85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('research_context_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('CREATED_AT IS NOT NULL', name='CONVERSATION_CREATED_NN'),
    sa.CheckConstraint('DELETED IS NOT NULL', name='CONVERSATION_DELETED_NN'),
    sa.CheckConstraint('UPDATED_AT IS NOT NULL', name='CONVERSATION_UPDATED_NN'),
    sa.ForeignKeyConstraint(['research_context_id'], ['research_context.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sender', sa.Enum('USER', 'AGENT', name='conversationsender'), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('CREATED_AT IS NOT NULL', name='MESSAGES_CREATED_NN'),
    sa.CheckConstraint('DELETED IS NOT NULL', name='MESSAGES_DELETED_NN'),
    sa.CheckConstraint('UPDATED_AT IS NOT NULL', name='MESSAGES_UPDATED_NN'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('conversation')
    # ### end Alembic commands ###
