"""create base models

Revision ID: d9841daf0019
Revises: 
Create Date: 2023-08-18 22:56:52.997707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9841daf0019'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lfn', sa.String(), nullable=True),
    sa.Column('protocol', sa.Enum('S3', 'NAS', 'LOCAL', name='protocolenum'), nullable=False),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('research_goals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('prada_tagger_node_id', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('prada_uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_contexts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('vector_store', sa.String(), nullable=True),
    sa.Column('research_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['research_id'], ['research_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('participants', sa.Enum('USER', 'AGENT', name='conversationsender'), nullable=False),
    sa.Column('research_context', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['research_context'], ['research_contexts.id'], ),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('vector_stores',
    sa.Column('vector_store_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lfn', sa.String(), nullable=True),
    sa.Column('protocol', sa.Enum('S3', 'NAS', 'LOCAL', name='protocolenum'), nullable=False),
    sa.Column('research_context_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['research_context_id'], ['research_contexts.id'], ),
    sa.PrimaryKeyConstraint('vector_store_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('source_documents_metadata', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('notes',
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('messages')
    op.drop_table('vector_stores')
    op.drop_table('conversations')
    op.drop_table('research_contexts')
    op.drop_table('research_goals')
    op.drop_table('documents')
    # ### end Alembic commands ###
