name: Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-dev libpq-dev # psycopg2
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run pytest
      run: |
        echo "OLD_HF_CACHE_HASH=$(find ~/.cache/huggingface ~/.cache/torch -type f -exec sha256sum {} + | LC_ALL=C sort | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_ENV
        poetry run pytest -s
        echo "NEW_HF_CACHE_HASH=$(find ~/.cache/huggingface ~/.cache/torch -type f -exec sha256sum {} + | LC_ALL=C sort | sha256sum | cut -d ' ' -f 1)" >> $GITHUB_ENV

    - name: Save new HF models to cache
      uses: actions/cache/save@v3
      with:
        path: |
          ~/.cache/huggingface
          ~/.cache/torch
        key: hf-models-${{ matrix.os }}-${{ env.NEW_HF_CACHE_HASH }}
      # Only save cache if the hash has changed
      if: ${{ env.NEW_HF_CACHE_HASH}} != ${{ env.OLD_HF_CACHE_HASH }}